export const PLAYER_STEP_SIZE = 10
export const PLAYER_SIZE = 25
export const PROJECTILE_STEP_SIZE = 15
export const SHOOTING_DELAY = 200
export const STAR_MAX_SIZE = 5
export const SCREEN_HEIGHT = window.innerHeight
export const SCREEN_WIDTH = window.innerWidth
export const FPS = 60
export const MS_PER_FRAME = 1000 / FPS
